config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  root to: "bikes#index"
  resources :bikes do
    resources :bookings, only: [:show, :new, :create]
  end
  get '/bookings', to: 'bookings#index', as: 'all_bookings'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  CATEGORIES = %w[City Electric] # Gravel Dirt Road City Trekking Mountain BMX]
  has_one_attached :photo
  belongs_to :user
  has_many :bookings

  validates :name, presence: true, length: { maximum: 255 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :location, presence: true

  include PgSearch::Model
pg_search_scope :search_by_location_and_category,
  against: [ :location, :category ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :user_id, presence: true
  validates :bike_id, presence: true
  validates :checkin, presence: true
  validates :checkout, presence: true
  validate :check_dates_order

  private

  def check_dates_order
    if checkin && checkout && checkin >= checkout
      errors.add(:base, 'Check-out date must be after check-in date')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

     # For additional in app/views/devise/registrations/edit.html.erb
     # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @bikes = Bike.search_by_location_and_category(params[:query])
    else
      @bikes = Bike.all
    end
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to @bike, notice: 'Bike was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # Assumes set_bike method sets @bike instance variable
  end

  def update
    # Assumes set_bike method sets @bike instance variable

    if @bike.update(bike_params)
      redirect_to @bike, notice: 'Bike was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bike.destroy
    redirect_to bikes_url, notice: 'Bike was successfully destroyed.'
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:name, :description, :price, :category, :photo, :location)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new
    @dates_to_disable = @bike
                      .bookings
                      .where('checkout > ?', Date.yesterday)
                      .pluck(:checkin, :checkout)
                      .map do |(checkin, checkout)|
                        { from: checkin, to: checkout }
                      end
  end

  def edit
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new(booking_params.except(:checkin))
    dates = booking_params[:checkin].split(' to ')
    checkin, checkout = dates
    @booking.checkin = Date.parse(checkin)
    @booking.checkout = Date.parse(checkout)
    @booking.user = current_user
    @booking.bike = @bike
    if @booking.save
      redirect_to bikes_path(@bikes), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :event_id, :checkin, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.erb
<%= bike.errors.messages if bike.errors.present? %>
<%= simple_form_for bike do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :location %>
  <%= f.input :category, collection: Bike::CATEGORIES %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "mb-5 btn btn-primary" %>
<% end %>

app/views/bikes/edit.html.erb
<%= render "form", bike: @bike %>

app/views/bikes/index.html.erb
<div class="wraper">
    <div class="banner p-4" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= image_url('bicycle.jpg') %>'); background-repeat: no-repeat; background-size: cover; background-position: center;">
      <div class="container">
        <h1 style="color: white;">Our bikes in Germany</h1>
        <p style="font-size: 16px; color: white; width: 400px; word-break: break-word;">
          Looking to buy a bike in Germany? Choose a Bikerent subscription instead. Our store provides a cool collection of city or electric bikes to choose from in unisex frames for women or men.
        </p>

        <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get" style="position: relative;">
          <div class="search-form-control form-group">
              <%# end of previous version %>
            <div class="row justify-content-left">
                <div class="col-sm-4 my-3">
                  <%= form_with url: bikes_path, method: :get, class: "d-flex searchbar" do %>
                    <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Search by city or category"%>
                    <%= submit_tag "Search", name: "", class: "btn btn-primary mt-2" %>
                  <% end %>
                </div>
           </div>
          </div>
        </form>
      </div>
    </div>
  <div class="container my-5">
    <div id="top" class="mb-2 d-flex justify-content-end">
      <%= link_to "Offer your bike", new_bike_path, class:"btn btn-primary" %>
    </div>
    <div class="cards">
      <% @bikes.each do |bike| %>
        <%= link_to bike_path(bike), class: "text-decoration-none" do %>
          <div class="card-bike">
            <div class=" d-flex justify-content-center align-items-center card-category"
              data-aos="zoom-in"
              style="background-image: linear-gradient(rgba(20,0,0,0.1), rgba(0,20,0,0.2)), url(<%= cl_image_path bike.photo.key, width: 400, height: 250, gravity: :auto, crop: :fill %>);
                object-fit: cover;">
            </div>
              <%# card info %>
            <div class="p-3">
              <p><strong>Name:</strong> <%= bike.name %></p>
              <p><strong>Location:</strong> <%= bike.location %></p>
              <p><strong>Price per Day:</strong> <%= bike.price %>€ / day</p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 mt-4 mb-4 shadow">
        <%= render "form", bike: @bike %>
       </div>
    </div>
</div>

app/views/bikes/show.html.erb
<div class="wraper center-middle">
  <div class="container container-show">
    <div class="position-relative">

    <div class="card-bike">
  <div class="card-category" style="background-image: url('<%= cl_image_path @bike.photo.key%>'); background-position: center;">
      </div>
      <div class="card-info p-3 d-flex justify-content-between align-items-start">
        <div>
          <h3><%= @bike.name %></h3>
          <p><%= @bike.description %></p>
        </div>
          <%= link_to "Rent Now", new_bike_booking_path(@bike), class: "btn btn-primary" %>
        </div>
    </div>
        <!-- Add a button to link to the booking website -->
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<body class="text-center">
    <div class="mt-5">
        <h1>My bookings</h1>
    </div>
<div class="wraper center-middle">
<% if @bookings.any? %>
  <table class="table table-white">
    <thead>
      <tr>
        <th>Bike</th>
        <th>Check-in</th>
        <th>Check-out</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.bike.name %></td>
          <td><%= booking.checkin %></td>
          <td><%= booking.checkout %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No bookings available.</p>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="wraper center-middle">
  <div class="container position-relative">
    <div class="card-bike">
      <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path @bike.photo.key%>'); background-position: center;">
      </div>

      <div class="p-3">

        <div data-controller='datepicker'
        data-datepicker-price-value='<%= @bike.price.to_json %>'
        data-datepicker-dates-to-disable-value="<%= @dates_to_disable.to_json %>">

          <div class="d-flex justify-content-between">

            <div>
              <h3><%= @bike.name %></h3>
              <p> Price:<strong> <span data-datepicker-target='priceDisplay'></span>€ in total </strong></p>
            </div>

            <div>
              <p><%= @bike.description %></p>
              <p><%= @bike.price %>€ / day</p>
            </div>

          </div>

          <%= simple_form_for [@bike, @booking ] do |f| %>
            <%= f.input :checkin, as: :string, input_html: { data: { datepicker_target: 'dateField' } } %>
            <%= f.button :submit, 'Create Booking', class: 'btn btn-primary' %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikerent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>

    <%= yield %>

  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Bike Rental in Germany since 2019.</p>
  </div>
  <span>🚵🏻‍♂️😊👌</span>
</div>

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "alttext", class: "logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://cdn3.iconfinder.com/data/icons/essential-rounded/64/Rounded-31-512.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", all_bookings_path, class: "dropdown-item" %>
              <%= link_to "😎 My Account", "#", class: "dropdown-item" %>
              <%= link_to "🆘 Help", "#", class: "dropdown-item" %>
              <%= link_to "🔒 Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>